version: "3"

services:
  traefik:
    container_name: traefik
    image: traefik:v2.0
    restart: always
    ports:
      - 8080:8080
      - 80:80
      - 443:443
    labels:
      - traefik.port=80
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - $PWD/traefik.yml:/etc/traefik/traefik.yml
      - $PWD/traefik.toml:/etc/traefik/traefik.toml
      - $PWD/acme.json:/acme.json
    networks:
        - proxy

networks:
    proxy:
        external: true
          